### ISSUE TITLE
aYO add dark mode

### ISSUE THREAD

**Issue by rethinkingrn** [RandoNandoz/knockoff-quizlet#1]
## Steps to Reproduce

1. Get program
2. Look at program
3. blind

## Context (Environment)

I have terrible vision
light mode  just cause me to become blind. 
## Detailed Description
Could you please add a dark mode for your program plz?

## Possible Implementation
Use dark reader on the program or something 
https://microsoftedge.microsoft.com/addons/detail/dark-reader/ifoakfbpdcdoeenechcleahebpibofpc
thanks MaN

**Comment by RandoNandoz** [comment]
You implement it


Randy

**Comment by RandoNandoz** [comment]
@rethinkingrn Okay, this actually can be implemented using CSS with JavaFX.

**Comment by RandoNandoz** [comment]
Commit cb6abfae17c610e1c9672fc8544c8419fc33dfbe closes this issue.
